import { z } from 'zod';

/**
 * Validation around the categories of the catalogue.
 *
 * Categories are a list the administrators keep: a product picks from it, it
 * does not invent its own. That is what keeps "Getränke", "getraenke" and
 * "Getränk" from turning into three filters for the same shelf. A product may
 * carry several of them - oat milk is a drink and it is vegan.
 */

export const CATEGORY_NAME_MAX_LENGTH = 60;

/**
 * How many categories one product may carry. Nobody files a yoghurt under
 * twenty headings on purpose; the bound only keeps a script from sending a
 * thousand identifiers in one request.
 */
export const PRODUCT_CATEGORIES_MAX = 20;

/** Identifiers are generated by the server; this only bounds what may arrive. */
const categoryIdSchema = z.string().trim().min(1).max(64);

export const categoryNameSchema = z.string().trim().min(1).max(CATEGORY_NAME_MAX_LENGTH);

/**
 * The categories of a product, as identifiers of the list. Duplicates are
 * folded rather than refused: ticking a box and picking the same entry from
 * the dropdown is one wish, not two.
 */
export const categoryIdsSchema = z
  .array(categoryIdSchema)
  .max(PRODUCT_CATEGORIES_MAX)
  .transform((ids) => [...new Set(ids)]);

/** Body of `POST /api/v1/categories`. */
export const createCategorySchema = z.object({
  name: categoryNameSchema,
  /** Shown as a checkbox on every product form instead of hiding in the dropdown. */
  frequent: z.boolean().default(false),
});

/** Body of `PATCH /api/v1/categories/:id`; at least one of the two. */
export const updateCategorySchema = z
  .object({
    name: categoryNameSchema.optional(),
    frequent: z.boolean().optional(),
  })
  .refine((value) => value.name !== undefined || value.frequent !== undefined, {
    message: 'no changes given',
  });

export type CreateCategoryInput = z.infer<typeof createCategorySchema>;
export type UpdateCategoryInput = z.infer<typeof updateCategorySchema>;
